name: discord
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  sembast: ^3.5.0+1
  args: ^2.4.2
  # crypto: ^3.0.1
  # password_hash: ^5.1.0
  # path: ^1.8.0
  bcrypt: ^1.1.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  dsc: discord